apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eightton-policy-ingress
  namespace: aiops-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Range"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: public-nginx
  rules:
  - host: eightton-policy.play.cloudzcp.net
    http:
      paths:
      - backend:
          service:
            name: eightton-policy
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - eightton-policy.play.cloudzcp.net
    secretName: wildcard-play-cloudzcp-net-cert
